/* eslint-disable */
// This file contains the raw Figma tokens provided by the user.
// In a real app, this might be fetched from an API or generated by a build script.

export const figmaTokens = [
  {
    "id": "VariableID:2539:13118",
    "name": "Color/Black and White/Black",
    "description": "",
    "type": "COLOR",
    "valuesByMode": { "20:0": { "r": 0, "g": 0, "b": 0, "a": 1 } }
  },
  {
    "id": "VariableID:2539:13122",
    "name": "Color/Black and White/White",
    "description": "",
    "type": "COLOR",
    "valuesByMode": { "20:0": { "r": 1, "g": 1, "b": 1, "a": 1 } }
  },
  {
    "id": "VariableID:2539:12785",
    "name": "Color/Brands/Old Navy/Brand 1",
    "description": "",
    "type": "COLOR",
    "valuesByMode": { "20:0": { "r": 0, "g": 0.21568627655506134, "b": 0.3921568691730499, "a": 1 } }
  },
  {
    "id": "VariableID:2539:13074",
    "name": "Color/Red/200",
    "description": "",
    "type": "COLOR",
    "valuesByMode": { "20:0": { "r": 0.8156862854957581, "g": 0, "b": 0, "a": 1 } }
  },
  {
    "id": "VariableID:2539:13377",
    "name": "Spacing/050",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 4 }
  },
  {
    "id": "VariableID:2539:13376",
    "name": "Spacing/100",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 8 }
  },
  {
    "id": "VariableID:2539:13385",
    "name": "Spacing/200",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 16 }
  },
  {
    "id": "VariableID:2539:13204",
    "name": "Border Radius/050",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 4 }
  },
  {
    "id": "VariableID:2539:13207",
    "name": "Border Radius/100",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 8 }
  },
  {
    "id": "VariableID:20:25525",
    "name": "Font/Size/14",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 14 }
  },
  {
    "id": "VariableID:20:25526",
    "name": "Font/Size/16",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 16 }
  },
  {
    "id": "VariableID:20:25529",
    "name": "Font/Size/24",
    "description": "",
    "type": "FLOAT",
    "valuesByMode": { "20:0": 24 }
  }
];
